# @package _global_

model:
  _target_: cdnp.model.ddpm.DDPM
  noise_scheduler:
    _target_: diffusers.DDPMScheduler
    num_train_timesteps: 1000
    beta_schedule: "linear"
    beta_start: 0.0001
    beta_end: 0.02
  loss_fn:
    _target_: torch.nn.MSELoss

execution:
  ema_rate: 0.9998