# @package _global_

model:
  backbone:
    block_out_channels: [128, 256, 512, 512]
    down_block_types:
      - DownBlock2D
      - AttnDownBlock2D
      - AttnDownBlock2D
      - AttnDownBlock2D
    up_block_types:
      - AttnUpBlock2D
      - AttnUpBlock2D
      - AttnUpBlock2D
      - UpBlock2D