defaults:
  - base
  - data: celeba
  - task: inpaint
  - model: ddpm
  - model/backbone: big
  - _self_

model:
  backbone:
    out_channels: 3 # RGB image
  
execution:
  epochs: 30

data:
  in_channels: 7 # noised RGB image + masked RGB input + mask
  preprocess_fn:
    min_frac: 0.05
    max_frac: 0.3