defaults:
  - base
  - data: celeba
  - task: inpaint
  - model: cdnp
  - model/backbone: big
  - _self_

model:
  noise_scheduler:
    num_train_timesteps: 20
  cnp:
    _target_: cdnp.util.instantiate.load_model_from_path
    path: ${paths.weights}/celeba_cnp
    freeze: true # Freeze the trained CNP
  backbone:
    in_channels: 13 # noised RGB image + masked RGB input + mask + CNP mean + CNP stddev
    out_channels: 3 # RGB image
  
execution:
  train_steps: 300000
  ema_rate: 0.9995

data:
  preprocess_fn:
    min_frac: 0.01
    max_frac: 0.1
  
output:
  plot_freq: 1000
  metrics:
    - _target_: cdnp.evaluate.LossMetric
    - _target_: cdnp.evaluate.FIDMetric      
      num_samples: 5000
      means: ${data.dataset.norm_means}
      stds: ${data.dataset.norm_stds}
      device: ${runtime.device}