defaults:
  - base
  - data: cifar10
  - task: inpaint
  - model: cdnp
  - model/backbone: big
  - _self_

model:
  cnp:
    _target_: cdnp.util.instantiate.load_model_from_path
    path: ${paths.weights}/2025-06-02_17-19_kind_bear
    freeze: true # Freeze the trained CNP
  backbone:
    in_channels: 13 # noised RGB image + masked RGB input + mask + CNP mean + CNP stddev
    out_channels: 3 # RGB image

data:
  preprocess_fn:
    min_frac: 0.1
    max_frac: 0.1

execution:
  train_steps: 300000

output:
  plot_freq: 3000
  metrics:
    - _target_: cdnp.evaluate.LossMetric
    - _target_: cdnp.evaluate.FIDMetric      
      num_samples: 5000
      means: ${data.dataset.norm_means}
      stds: ${data.dataset.norm_stds}
      device: ${runtime.device}