defaults:
  - base
  - data: cifar10
  - task: inpaint
  - model: ddpm
  - model/backbone: big
  - _self_

model:
  backbone:
    out_channels: 3 # RGB image
  
execution:
  train_steps: 300000
  gradient_clip_norm: 1.0

data:
  in_channels: 7 # noised RGB image + masked RGB input + mask
  preprocess_fn:
    min_frac: 0.1
    max_frac: 0.1

output:
  metrics:
    - _target_: cdnp.evaluate.LossMetric
    - _target_: cdnp.evaluate.FIDMetric      
      num_samples: 100
      means: ${data.dataset.norm_means}
      stds: ${data.dataset.norm_stds}
      device: ${runtime.device}