defaults:
  - base
  - data: cifar10
  - task: inpaint
  - model: cnp
  - model/backbone: small
  - model_type: deterministic
  - _self_

data:
  in_channels: 4 # masked RGB input + mask
  preprocess_fn:
    min_frac: 0.05
    max_frac: 0.2

model:
  backbone:
    out_channels: 18 # 2*C + C*rank = 2*3 + 3*4 = 18
  min_std: 0.01
  device: ${runtime.device}
  correlation_rank: 4
