defaults:
  - base
  - data: cifar10
  - task: ccgen
  - model: ddpm
  - model/backbone: big
  - _self_

execution:
  train_steps: 300000

data:
  preprocess_fn:
    _target_: cdnp.task.preprocess_ccgen
    _partial_: true

output:
  metrics:
    - _target_: cdnp.evaluate.LossMetric
    - _target_: cdnp.evaluate.FIDMetric      
      num_samples: 100
      means: ${data.dataset.norm_means}
      stds: ${data.dataset.norm_stds}
      device: ${runtime.device}