defaults:
  - base
  - data: cifar10
  - task: ccgen
  - model: ddpm
  - model/backbone: big
  - _self_

execution:
  epochs: 100

data:
  preprocess_fn:
    _target_: cdnp.task.preprocess_ccgen
    _partial_: true