defaults:
  - base
  - data: cifar10
  - task: inpaint
  - model: ddpm
  - model/backbone: big
  - _self_

model:
  backbone:
    out_channels: 3 # RGB image
  
execution:
  epochs: 100

data:
  in_channels: 7 # noised RGB image + masked RGB input + mask