defaults:
  - base
  - data: cifar10
  - task: inpaint
  - _self_

model:
  model:
    block_out_channels: [128, 256, 512, 512]
    down_block_types:
      - DownBlock2D
      - AttnDownBlock2D
      - AttnDownBlock2D
      - AttnDownBlock2D
    up_block_types:
      - AttnUpBlock2D
      - AttnUpBlock2D
      - AttnUpBlock2D
      - UpBlock2D
    out_channels: 3 # RGB image
    num_class_embeds: null # No class labels for this task
  
execution:
  epochs: 100

data:
  in_channels: 7 # noised RGB image + masked RGB input + mask