defaults:
  - base
  - data: cifar10
  - task: imgen
  - model: ddpm
  - model/backbone: big
  - _self_

model:
  backbone:
    out_channels: 3 # RGB image

execution:
  train_steps: 300000
  gradient_clip_norm: 1.0

data:
  in_channels: 3 # noised RGB image

output:
  metrics:
    - _target_: cdnp.evaluate.LossMetric
    - _target_: cdnp.evaluate.FIDMetric
      num_samples: 100
      device: ${runtime.device}