defaults:
  - base
  - data: era5_wind
  - task: forecast
  - model: flow_matching_no_attention
  - _self_

model:
  backbone:
    in_channels: 11 # 2 context times * 2 variables + 5 static + 2 random noise
    out_channels: 2 # 2 v-fields
  
execution:
  train_steps: 3000000
  gradient_clip_norm: 3.0
  ema_rate: 0.999

data:
  trainloader:
    batch_size: 4
  testloader:
    batch_size: 8

optimizer:
  lr: 1e-4
  betas: [0.9, 0.95]