defaults:
  - base
  - data: era5
  - task: forecast
  - model: cnp
  - model/backbone: big_no_attention
  - _self_

model:
  residual: true
  backbone:
    #in_channels: 201 # 2 context times * 82 variables + 5 static + 32 time embeds
    in_channels: 39 # 2 context times * 1 variables + 5 static + 32 time embeds
    #output_dimension: 164 # T2M mean and std * 82 trg variables
    #output_dimension: 2 # T2M mean and std * 1 trg variable
    out_channels: 2 # T2M mean and std * 1 trg variable
  min_std: 0.01
  
execution:
  train_steps: 50000

data:
  trainloader:
    batch_size: 4
  testloader:
    batch_size: 8

optimizer:
  lr: 1e-4