defaults:
  - base
  - data: mnist
  - task: ccgen
  - model: ddpm
  - model/backbone: small
  - _self_

execution:
  epochs: 20

data:
  preprocess_fn:
    _target_: cdnp.task.preprocess_ccgen
    _partial_: true