defaults:
  - base
  - data: mnist
  - task: inpaint
  - model: cnp
  - model/backbone: small
  - _self_

data:
  in_channels: 2 # masked input + mask

model:
  backbone:
    out_channels: 2 # Predicted mean + predicted stddev

execution:
  epochs: 20 