defaults:
  - base
  - data: mnist
  - task: inpaint
  - model: ddpm
  - model/backbone: small
  - _self_

model:
  backbone:
    out_channels: 1 # Just the greyscale image
  
execution:
  epochs: 20

data:
  in_channels: 3 # noised greyscale image + masked input + mask
 