defaults:
  - base
  - data: mnist
  - task: inpaint
  - model: cdnp
  - model/backbone: small
  - _self_

model:
  cnp:
    _target_: cdnp.util.instantiate.load_model_from_path
    path: ${paths.weights}/2025-05-28_10-29_kind_hippo
    freeze: true # Freeze the trained CNP
  backbone:
    in_channels: 3 # noised greyscale image + masked input + mask
    out_channels: 1 # Just the greyscale image
 
execution:
  epochs: 20
 