# @package _global_

output:
  plotter:
    _target_: cdnp.plot.plotter.CcgenPlotter
    _partial_: true
    device: ${runtime.device}
    num_samples: 2
    num_classes: ${data.num_classes}
    norm_means: ${data.dataset.norm_means}
    norm_stds: ${data.dataset.norm_stds}