# @package _global_

output:
  plotter:
    _target_: cdnp.plot.plotter.ImgenPlotter
    _partial_: true
    device: ${runtime.device}
    num_samples: 4

data:
  preprocess_fn:
    _target_: cdnp.task.preprocess_imgen
    _partial_: true