defaults: 
  - /generative_model: flow_matching
  - _self_

_target_: cdnp.model.warm_start_diffusion.WarmStartDiffusion
device: ${runtime.device}
warm_start_model: ???
min_warmth: 0.0
max_warmth: 1.0
min_std: 0.01
loss_weighting: false