name: ci-run-tests-pr-main
on:
  # Runs workflow whenever a pull request to main is opened and whenever changes are
  # pushed to the branch associated with the pull request
  pull_request:
    branches: ["main"]
    types: [opened, synchronize]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pip install uv
          pdm config use_uv true

      - name: Install dependencies with PDM
        run: pdm install

      - name: Check formatting with Ruff
        run: pdm run ruff format --check src tests

      - name: Lint with Ruff
        run: pdm run ruff check src tests

      - name: Type-check with ty
        run: pdm run ty check src tests

      - name: Run tests with Pytest
        run: pdm run pytest tests
